name: Scheduled Node.js Job

on:
  schedule:
    - cron: '45 12 * * *'  # Runs the job everyday  minutes (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.0'  # Specify your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run index.js with cron jobs
        run: node index.js  # Replace 'index.js' with your Node.js script name and location
